name: p37env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - numpy=1.20.3=py37ha4e8547_0
  - openpyxl=3.0.9=pyhd3eb1b0_0
  - pandas=1.3.2=py37h6214cd6_0
  - plotly=4.14.3=pyhd3eb1b0_0